 ques 1. Write a function so that the columns of the output matrix are powers of the input
vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.

In [14]:
import numpy as np
def gen_vander_matrix(iv, n, increasing=False):
    if not increasing:
        om = np.array([x**(n-1-i) for x in iv for i in range(n)]).reshape(iv.size,n)
    elif increasing:
        om = np.array([x**i for x in iv for i in range(n)]).reshape(iv.size,n)
    return om
inputvector = np.array([1,3,6,9,12,15])
ncol_om = 4
om_dec_order = gen_vander_matrix(inputvector,ncol_om,False)
om_inc_order = gen_vander_matrix(inputvector,ncol_om,True)
print("In decresing order :\n" ,om_dec_order,"\n")
print("In increasing order :\n" ,om_inc_order,"\n")

In decresing order :
 [[   1    1    1    1]
 [  27    9    3    1]
 [ 216   36    6    1]
 [ 729   81    9    1]
 [1728  144   12    1]
 [3375  225   15    1]] 

In increasing order :
 [[   1    1    1    1]
 [   1    3    9   27]
 [   1    6   36  216]
 [   1    9   81  729]
 [   1   12  144 1728]
 [   1   15  225 3375]] 



ques 2. : Write a function to find moving average in an array over a window:
 Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [15]:
def moveave(ml, N):
    s, mov_av = [0], []
    for i, x in enumerate(ml, 1):
        s.append(s[i-1] + x)
        if i>=N:
            p = round(((s[i] - s[i-N])/N),2) 
            mov_av.append(p)
    print( mov_av)

In [16]:
ml = [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
N = 3
moveave(ml,N)

[5.0, 4.67, 5.67, 6.67, 9.67, 28.67, 49.33, 72.67, 84.0, 93.33, 116.33]
